spring:
  application:
    name: people-service


  datasource:
    url: jdbc:postgresql://localhost:5432/acadnest
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  host: 0.0.0.0
  port: 8082

eureka:
  instance:
    hostname: localhost   # ✅ Forces Eureka to register as localhost
    prefer-ip-address: false  # ✅ Uses hostname instead of IP
    instance-id: ${spring.application.name}:${server.port}  # ✅ Unique instance ID
  client:
    register-with-eureka: true
    fetch-registry: true


logging:
  file:
    name: .././logs/people-service.log
  level:
    root: DEBUG
    org.springframework.web: ERROR
    org.hibernate: ERROR
    com.project.acadNest: DEBUG
    jdk.event.security: OFF
    org.apache.hc.client5.http: OFF
    org.apache.hc.client5.http.wire: OFF
    org.apache.hc.client5.http.headers: OFF
    org.apache.hc.client5.http.impl.classic: OFF
    org.apache.hc.client5.http.protocol: OFF
    org.springframework.cloud.client.discovery: WARN
    com.netflix.discovery: WARN
  pattern:
    console: ""