server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: people-service
          uri: lb://PEOPLE-SERVICE
          predicates:
            - Path=/api-gateway/people/**
          filters:
            - StripPrefix=1  # Removes '/api-gateway' before forwarding

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api-gateway/auth/**
          filters:
            - StripPrefix=1  # Removes '/api-gateway' before forwarding

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


logging:
  file:
    name: .././logs/api-gateway.log
  level:
    root: DEBUG
    org.springframework: INFO
    org.springframework.cloud.gateway: ERROR
    org.hibernate: ERROR
    com.netflix.discovery: ERROR
    reactor.netty: DEBUG
    org.apache.hc.client5: ERROR
    com.project.acadNest: DEBUG
    jdk.event.security: OFF
  pattern:
    console: ""
