spring:
  application:
    name: api-gateway

  datasource:
    url: jdbc:postgresql://localhost:5432/api_gateway
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db.changelog/db.changelog.xml

server:
  host: 0.0.0.0
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  file:
    name: .././logs/api-gateway.log
  level:
    root: DEBUG
    org.springframework.web: ERROR
    org.hibernate: ERROR
    com.project.acadNest: DEBUG
    jdk.event.security: OFF
  pattern:
    console: ""
